
export const SET_NEXT_PAGE='SET_NEXT_PAGE';
export const SET_MODAL_FLAG='SET_MODAL_FLAG';
export const SET_PRODUCT_RESULT='SET_PRODUCT_RESULT';
export const SET_ANSWERS_CHOSEN ='SET_ANSWERS_CHOSEN';
export const SET_SUB_ANSWER_CHOSEN = 'SET_SUB_ANSWER_CHOSEN';
export const SET_NO_PRODUCT_MODAL_FLAG = 'SET_NO_PRODUCT_MODAL_FLAG';